'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ApcsWebServiceSoap")>  _
    Public Interface ApcsWebServiceSoap
        
        'CODEGEN: Generating message contract since element name mcNo from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LotRptIgnoreError", ReplyAction:="*")>  _
        Function LotRptIgnoreError(ByVal request As ServiceReference1.LotRptIgnoreErrorRequest) As ServiceReference1.LotRptIgnoreErrorResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIgnoreErrorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIgnoreError", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.LotRptIgnoreErrorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.LotRptIgnoreErrorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIgnoreErrorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public mcNo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public errorCode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mcNo As String, ByVal errorCode As String)
            MyBase.New
            Me.mcNo = mcNo
            Me.errorCode = errorCode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIgnoreErrorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIgnoreErrorResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.LotRptIgnoreErrorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.LotRptIgnoreErrorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIgnoreErrorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LotRptIgnoreErrorResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LotRptIgnoreErrorResult As Boolean)
            MyBase.New
            Me.LotRptIgnoreErrorResult = LotRptIgnoreErrorResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ApcsWebServiceSoapChannel
        Inherits ServiceReference1.ApcsWebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ApcsWebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ApcsWebServiceSoap)
        Implements ServiceReference1.ApcsWebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_ApcsWebServiceSoap_LotRptIgnoreError(ByVal request As ServiceReference1.LotRptIgnoreErrorRequest) As ServiceReference1.LotRptIgnoreErrorResponse Implements ServiceReference1.ApcsWebServiceSoap.LotRptIgnoreError
            Return MyBase.Channel.LotRptIgnoreError(request)
        End Function
        
        Public Function LotRptIgnoreError(ByVal mcNo As String, ByVal errorCode As String) As Boolean
            Dim inValue As ServiceReference1.LotRptIgnoreErrorRequest = New ServiceReference1.LotRptIgnoreErrorRequest()
            inValue.Body = New ServiceReference1.LotRptIgnoreErrorRequestBody()
            inValue.Body.mcNo = mcNo
            inValue.Body.errorCode = errorCode
            Dim retVal As ServiceReference1.LotRptIgnoreErrorResponse = CType(Me,ServiceReference1.ApcsWebServiceSoap).LotRptIgnoreError(inValue)
            Return retVal.Body.LotRptIgnoreErrorResult
        End Function
    End Class
End Namespace
